# Generated by Django 4.1.5 on 2023-01-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Exams',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.exam')),
            ],
            options={
                'verbose_name_plural': 'Months',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.exam')),
            ],
            options={
                'verbose_name_plural': 'Years',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.exam')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.year')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.exam')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.month')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.year')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.year'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.exam')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.month')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam_api.year')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
    ]
