# Generated by Django 4.1.5 on 2023-01-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "Exams",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MAY/JUN", "MAY/JUNE"),
                            ("JUN/JUL", "JUNE/JULY"),
                            ("OCT/NOV", "OCTOBER/NOVEMBER"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="months",
                        to="exam_api.exam",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Months",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=255)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="years",
                        to="exam_api.exam",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Years",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("General Mathematics", "General Mathematics"),
                            ("Further Mathematics", "Further Mathematics"),
                            ("English Language", "English Language"),
                            ("Economics", "Economics"),
                            ("Physics", "Physics"),
                            ("Biology", "Biology"),
                            ("Chemistry", "Chemistry"),
                            ("Geography", "Geography"),
                            ("Government", "Government"),
                            ("Commerce", "Commerce"),
                            ("Accounting", "Accounting"),
                            ("History", "History"),
                            ("Agricultural Science", "Agricultural Science"),
                            ("Management", "Management"),
                            ("Civics", "Civics"),
                            ("Computer Science", "Computer Science"),
                            ("Marketing", "Marketing"),
                            ("English Literature", "English Literature"),
                            ("Islamic Studies", "Islamic Studies"),
                            (
                                "Christian Religious Studies",
                                "Christian Religious Studies",
                            ),
                            ("Hausa", "Hausa"),
                            ("Igbo", "Igbo"),
                            ("Yoruba", "Yoruba"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subjects",
                        to="exam_api.exam",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subjects",
                        to="exam_api.month",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subjects",
                        to="exam_api.year",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subjects",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(db_index=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="questions",
                        to="exam_api.exam",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="questions",
                        to="exam_api.month",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="questions",
                        to="exam_api.subject",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="questions",
                        to="exam_api.year",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Questions",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="month",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="months",
                to="exam_api.year",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_1", models.CharField(default=None, max_length=255)),
                ("option_2", models.CharField(default=None, max_length=255)),
                ("option_3", models.CharField(default=None, max_length=255)),
                ("option_4", models.CharField(default=None, max_length=255)),
                ("answer", models.CharField(default=None, max_length=255)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="exam_api.exam",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="exam_api.month",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="exam_api.question",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="exam_api.subject",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="exam_api.year",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Answers",
                "ordering": ["id"],
            },
        ),
    ]
