# Generated by Django 4.1.5 on 2023-01-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="years",
                to="exam_api.year",
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="years",
                to="exam_api.exam",
            ),
        ),
    ]
