# Generated by Django 4.1.5 on 2023-01-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0002_alter_month_year_alter_year_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="months",
                to="exam_api.year",
            ),
        ),
    ]
