# Generated by Django 4.1.5 on 2023-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0002_remove_answer_correct_remove_answer_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.IntegerField(),
        ),
    ]
