# Generated by Django 4.1.5 on 2023-01-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0004_alter_month_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="exam_name",
        ),
        migrations.AddField(
            model_name="subject",
            name="exam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="exam_api.exam",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="exam_api.month",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="exam_api.year",
            ),
        ),
    ]
