# Generated by Django 4.1.5 on 2023-01-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0006_alter_question_exam_alter_question_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="question",
            name="month",
        ),
        migrations.RemoveField(
            model_name="question",
            name="year",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="year",
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="exam_api.question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="exam_api.subject",
            ),
        ),
    ]
