# Generated by Django 4.1.5 on 2023-01-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0007_remove_question_exam_remove_question_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="month",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="year",
        ),
    ]
