# Generated by Django 4.1.5 on 2023-01-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0009_rename_answer_answer_text_alter_exam_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.IntegerField(unique=True),
        ),
    ]
