# Generated by Django 4.1.5 on 2023-01-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0011_alter_month_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.CharField(
                choices=[(2020, 2020), (2021, 2021), (2022, 2022)],
                default=None,
                max_length=20,
                unique=True,
            ),
        ),
    ]
