# Generated by Django 4.1.5 on 2023-01-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0012_subject_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="name",
            field=models.CharField(
                choices=[
                    ("MAY/JUN", "MAY/JUNE"),
                    ("JUN/JUL", "JUNE/JULY"),
                    ("OCT/NOV", "OCTOBER/NOVEMBER"),
                    ("Others", "Others"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="exam_api.year",
            ),
        ),
    ]
