# Generated by Django 4.1.5 on 2023-01-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0014_subject_yearsss"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="yearsss",
        ),
    ]
