# Generated by Django 4.1.5 on 2023-01-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_api", "0015_remove_subject_yearsss"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="exam_api.exam",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="month",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="exam_api.month",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="exam_api.year",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="exam_api.exam",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="month",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="exam_api.month",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="exam_api.year",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="exam_api.exam",
            ),
        ),
    ]
